# CI/CD File for Deploying a Hexo Site to Gitlab Pages.
image: node:8.11.4

# Cache modules across all branches and jobs
cache:
  key: Project
  paths:
  - node_modules/

stages:
  - build

before_script:
  - npm install

pages:
  stage: build
  script:
    - ./node_modules/hexo/bin/hexo generate
  artifacts:
    paths:
    - public
