# CI/CD File for Deploying a Hexo Site to Gitlab Pages.
image: node:8.11.4

# Cache modules across all branches and jobs
cache:
  key: Project
  paths:
  - node_modules/

stages:
  - build

before_script:
  - npm install
  - npm install -g staticrypt

pages:
  stage: build
  script:
    - ./node_modules/hexo/bin/hexo generate
    - mv public/resume/index.html public/resume/index_tmp.html
    - staticrypt public/resume/index_tmp.html $PASS -o public/resume/index.html 
    - rm public/resume/index_tmp.html
  artifacts:
    paths:
    - public
